version: '3'

services:
  docker-mongo:
    image: mongo
    expose:
    - 27017

  server:
    image: temperature-server
    build:
      ./server
    links:
    - docker-mongo
    expose:
    - 8080
    environment:
    - DATABASE_HOST=mongodb://docker-mongo/

  client:
    image: temperature-client
    build:
      ./client
    links:
    - server
    expose:
    - 3000
